### ISSUE TITLE
[BUG] [Crashdump] Filmmaker crashes upon loading map

### ISSUE THREAD

**Issue by FlashFried** [Silverlan/pfm#11]
Pragma / PFM Version: 9839434 v1.0.5 Win64

Pragma Filmmaker game mode crashes upon loading a map.

I expected it to load into the editor without issues

**Hardware (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA RTX 2070
 - GPU Driver version: 546.29

[pragma.exe.dmp](https://github.com/Silverlan/pfm/files/13762594/pragma.exe.dmp)

My Pragma folder doesn't have any outside files in it.

**Comment by Silverlan** [comment]
Thanks for the report! v1.0.5 is a really old version, could you try the latest stable one instead:
https://github.com/Silverlan/pragma/releases/latest

**Comment by Silverlan** [comment]
Closing this for now. If the issue remains with the latest version, just leave a comment and I'll re-open it.

**Comment by OfficeGeek888** [comment]
It still crashes in the updated version.

**Comment by Silverlan** [comment]
> It still crashes in the updated version.

In that case, could you please upload the crashdump for the new version?

**Comment by OfficeGeek888** [comment]
[crashdump_2024-01-16_12-20-23.zip](https://github.com/Silverlan/pfm/files/13954320/crashdump_2024-01-16_12-20-23.zip)

**Comment by FlashFried** [comment]
The issue was not resolved. It still crashed even with the new version

**Comment by Silverlan** [comment]
> The issue was not resolved. It still crashed even with the new version.
> 
> Open this issue back up

Hm.. Alright, please try this:
1) Download the latest version from https://github.com/Silverlan/pragma/releases/tag/nightly
2) Extract it to an empty directory
3) Try launching pragma.exe
4) If that works, exit, then try launching pfm.exe

If it still crashes, please upload the new crashdump.

**Comment by FlashFried** [comment]
Both started without problems. I might just be having conflicts with the patreon build.

**Comment by Silverlan** [comment]
> [@Silverlan](https://github.com/Silverlan) fix it plz

Can you please try the preview/nightly release?
https://github.com/Silverlan/pragma/releases/tag/nightly

If it still crashes, please upload the new crashdump.
This version is still work-in-progress though, so if it works, there may be other issues.

**Comment by vegabanbes** [comment]
@Silverlan this crashdump is from the new version

**Comment by Silverlan** [comment]
> [@Silverlan](https://github.com/Silverlan) this crashdump is from the new version

The crashdump says it's from Pragma v1.2.1 (released on 2023-10-29), which is a very old version. Where did you download it?

**Comment by Silverlan** [comment]
Closed due to inactivity.
If the issue still occurs with the [latest nightly version](https://github.com/Silverlan/pragma/releases/tag/nightly), please attach a new crashdump and I will re-open.

**Comment by Vantablack0000** [comment]
> Thanks for the report! v1.0.5 is a really old version, could you try the latest stable one instead and see if it still happens with that?: https://github.com/Silverlan/pragma/releases/latest

dawg, I've just installed this version and it's not even opening XD

**Comment by Vantablack0000** [comment]
> > The issue was not resolved. It still crashed even with the new version.
> > Open this issue back up
> __
> Hm.. Alright, please try this:
> 
> 1. Download the latest version from https://github.com/Silverlan/pragma/releases/tag/nightly
> 2. Extract it to an empty directory
> 3. Try launching pragma.exe
> 4. If that works, exit, then try launching pfm.exe
> 
> If it still crashes, please upload the new crashdump.

_not the NIGHTLY versions!_ those seem to be the buggiest in my experience
