### ISSUE TITLE
Web Browser not displaying sites correctly 

### ISSUE THREAD

**Issue by Yearlll** [Silverlan/pfm#12]
**General**
 - Pragma / PFM Version [e.g. "v0.4.2, d8c55ed [P v1.0.5 Win64]"]

**Describe the bug**
Its just showing up weirdly, might be the AMD apu I'm using?

**To Reproduce**
Simply open Pragma's built in browser

**Expected behavior**
A clear view of the site I want to load

**Screenshots**
![Screenshot 2024-04-16 151714](https://github.com/Silverlan/pfm/assets/77688052/9d2bd01c-030e-40cf-993d-545f576611a1)

**Hardware**
 - OS: [Windows 11]
 - GPU: [AMD Ryzen 5 5500U with Radeon Graphics, 2100 Mhz, 6 Cores, 12 Logical Processors]
 - GPU Driver version: [24.3.1]

**Comment by Silverlan** [comment]
Hey! Thanks for the report!
It's a known issue with AMD GPUs, haven't had time to look into it yet, but there's a simple workaround for now:
Try resizing the web browser window by a single pixel by dragging the handle slightly and it should show up correctly.

**Comment by Yearlll** [comment]
thanks for the blazing quick response lol,
full screening it seems to work. 
thanks mate!!

**Comment by Silverlan** [comment]
Should be fixed with the next update! Thanks again!
