### ISSUE TITLE
Vertical camera movement

### ISSUE THREAD

**Issue by JohnnyG4** [Silverlan/pfm#13]
I've already asked this on Youtube, but considering that you mentioned this site, here i go. You know that in Source Filmmaker and Blender have a way to move around in a vertical way (Z and X in SFM, SHIFT and mouse mid button in Blender), so considering that Pragma Filmmaker is also a animation software, don't you that it's fair to also have such option somehow?

DLDR: A way for the user to move themselves vertically should be added.

**Comment by Silverlan** [comment]
https://github.com/user-attachments/assets/5b1b046f-d1ad-483a-8ebd-fd9f1afced59

I've added several new camera control methods:
- By pressing the middle mouse button you can rotate the camera around the pivot
- If you hold shift, you can pan the camera
- The mouse wheel can be used to change the distance to the pivot position

Will be available with the next update! Thanks for the feedback!

**Comment by Silverlan** [comment]
Now available in the latest release:
https://github.com/Silverlan/pragma/releases/download/nightly/pragma-win64.zip
