### ISSUE TITLE
SFM Import Crash

### ISSUE THREAD

**Issue by JohnnyG4** [Silverlan/pfm#14]
I was trying to import Petruz's Rudy and Warfaremachine's Holly Zanzibar to PFM in different occasions, but both of them crashed the software for some reason, can you see what's happening?

[crashdump_2024-07-11_10-01-14.zip](https://github.com/user-attachments/files/16177544/crashdump_2024-07-11_10-01-14.zip)
[crashdump_2024-07-11_10-05-46.zip](https://github.com/user-attachments/files/16177547/crashdump_2024-07-11_10-05-46.zip)

**Comment by Silverlan** [comment]
Thanks for the crash dumps!
Should be fixed with the latest release:
https://github.com/Silverlan/pragma/releases/download/nightly/pragma-win64.zip

Please let me know if it's still a problem.
