### ISSUE TITLE
Orientation Extra Options

### ISSUE THREAD

**Issue by JohnnyG4** [Silverlan/pfm#16]
You probably know the pain in the butt that is to move a model in SFM when you're trying to move in a specific direction but arrows/lines positions don't cooperate, making everything harder, so, using blender as a base, how about adding some extra options for orientations?

**Comment by Silverlan** [comment]
Not sure what you mean. You can press the x/y/z keys to move something on a specific axis only.
Can you show me an example in Blender?

**Comment by JohnnyG4** [comment]
Maybe this can help https://youtu.be/ABayYXu7OfI?feature=shared

**Comment by Silverlan** [comment]
> Maybe this can help https://youtu.be/ABayYXu7OfI?feature=shared

You can switch between global/local/screen space in PFM by pressing the move or rotation tool multiple times (or by changing it in the settings to the right of the viewport). The viewport tutorial covers this iirc.

**Comment by JohnnyG4** [comment]
Nevermind then, thanks for the patience.
