### ISSUE TITLE
.GLB Strange Issue.

### ISSUE THREAD

**Issue by JohnnyG4** [Silverlan/pfm#17]
I noticed that it has some blender models that when they're imported to PFM via .GLB, they have a weird problem of missing something from it, usually the right part of something that comes in pairs (gloves, shoes, boots, etc.), do you mind see what is going on?

P. S. My best examples are Officer Flint (i used the V2 in this case), Alilkira and Rivet (all of them are from Warfaremachine) which can be found in Smutbase.
![Captura de tela 2024-07-20 095516-edit](https://github.com/user-attachments/assets/6d89104a-64e6-4b9e-9588-1f3921fef593)
![Captura de tela 2024-07-20 111314-edit](https://github.com/user-attachments/assets/ab8da318-87f4-4553-a99a-945ad78bcb1f)

**Comment by JohnnyG4** [comment]
I see, thanks anyway.

**Comment by Silverlan** [comment]
> I see, thanks anyway.

I gave it another look, it seems that the glTF exporter has problems with the mirror modifiers:

![blender_ymMxJDZrUs](https://github.com/user-attachments/assets/5c4ad825-6ad9-45e9-8111-9b2434ea4993)

The solution would be to apply the mirror modifier:

![blender_uzEqTY508Q](https://github.com/user-attachments/assets/5f92f823-8974-40a6-b0c9-8b41fb36e438)

Unfortunately that results with this error:
```Modifier cannot be applied to a mesh with shape keys```

I found this addon that may work, but I haven't tested it:
https://github.com/przemir/ApplyModifierForObjectWithShapeKeys

**Comment by JohnnyG4** [comment]
He gave some advices https://github.com/KhronosGroup/glTF-Blender-IO/issues/2290#issuecomment-2247333047

**Comment by Silverlan** [comment]
> He gave some advices [KhronosGroup/glTF-Blender-IO#2290 (comment)](https://github.com/KhronosGroup/glTF-Blender-IO/issues/2290#issuecomment-2247333047)

Yup, just tried it, that did the trick. Thanks for the info!
Strange that that option isn't enabled by default though.
