### ISSUE TITLE
Flex paralleling

### ISSUE THREAD

**Issue by JohnnyG4** [Silverlan/pfm#19]
I've found the GMod addon below recently, and i thought that i should share it with as a idea for Pragma, i mean, do you know how easy would be for the animators? If it already has, you can ignore it.

https://steamcommunity.com/sharedfiles/filedetails/?id=282164100

**Comment by Silverlan** [comment]
> I've found the GMod addon below recently, and i thought that i should share it with as a idea for Pragma, i mean, do you know how easy would be for the animators? If it already has, you can ignore it.
> 
> https://steamcommunity.com/sharedfiles/filedetails/?id=282164100

PFM should already do that, if you attach something to an actor via drop, it gets both bone-merged and flex-merged (assuming there are compatible flexes) ;).
