### ISSUE TITLE
Fix incorrect source engine model rotations

### ISSUE THREAD

**Issue by Silverlan** [Silverlan/pfm#2]
Some source engine models appear to have an incorrect rotation after being ported to Pragma. I don't know what causes it and how to determine which models are affected.

**Comment by donovan1212** [comment]
What ones? If it is just the sentries from mtt_engineer then it actually works as intended. The models were changed and it broke the sentry gun's animation.
[Proof](https://steamcommunity.com/app/1840/discussions/0/1696048426805286757/)

**Comment by Silverlan** [comment]
Completely forgot about this, but yeah, already fixed the issue a while back.
