### ISSUE TITLE
Textures not appearing

### ISSUE THREAD

**Issue by JohnnyG4** [Silverlan/pfm#21]
I was about to test Warfaremachine's Krystal and Miyu but after i import them, they both end up looking like in the picture below, can you see what is happening?
For tests use this https://drive.google.com/drive/folders/1KwfRzS3X4vCFlHEVp1JkYQ68N9oqSR3-?usp=sharing
P.S. Carmelita's pack is for Miyu's earing, or else it gets black.
![Captura de tela 2024-08-21 121536](https://github.com/user-attachments/assets/4a31813d-9be4-445f-b6a7-b4fe283ab03a)
And also, this pack might help with another issue that i told you some days ago, the one about the models having some parts missing.
![Captura de tela 2024-08-17 171244](https://github.com/user-attachments/assets/fc6430d2-3e53-4198-8fce-d978d029bbb1)

**Comment by JohnnyG4** [comment]
I almost forgot, Krystal's pack need this password to open.
KeepThatSandwichAwayFromMe9645414527562

**Comment by Silverlan** [comment]
The orange/black checkerboard pattern means it can't find the materials. I took a look and it seems that the materials for the model are not actually valid.
For example, if you open `materials/models/fursonas/StarFox/krystal/Ariete.vmt` in a text-editor, you'll get this:
```
"VertexLitGeneric"
{
	"$basetexture" "models\fursonas\StarFox\krystal/Ariete"
	"$bumpmap" 		"models\fursonas\StarFox\krystal/Nariete"
			//"$detail "models/fursonas/Angelawm/detailfur" 
$basemapalphaphongmask 1

	"$model" 					"1"
	"$phong" "1"
	"$phongexponent" "6"
	"$phongboost" "1"



	"$phongfresnelranges"		"[0.5 6 10]"

	"$ambientocclusion" 		"1"

	"$cloakPassEnabled" 		"1"
	    $rimlight 1
    $rimlightexponent 1
    $rimlightboost .5

		$envmap				"models\fursonas\StarFox\krystal/softgold.hdr" 
	$envmaptint			"[.3 .3 .3]"
}
}
```

There are two closing brackets (`}`)at the end, but there should only be one. Same for some of the other materials.
Some of them are missing the closing bracket altogether.

If you fix the closing brackets in the materials and try again, it should work. You may have to remove the files from `pragma/addons/imported/materials/` and `pragma/addons/converted/materials/` though.

**Comment by JohnnyG4** [comment]
I see, so it was the creator's unintentional doing, thanks anyway!
