### ISSUE TITLE
Project Import Crash

### ISSUE THREAD

**Issue by JohnnyG4** [Silverlan/pfm#22]
I don't know if this is fixed in the nighty version, but if not, it seems that when i was trying to a project (.dmx) from SFM to PFM, PFM simply crashed.
[crashdump_2024-10-21_17-15-41.zip](https://github.com/user-attachments/files/17466558/crashdump_2024-10-21_17-15-41.zip)

**Comment by Silverlan** [comment]
Thanks for the report! It looks like it crashes when trying to load this model: `fursonas/hornypolice/officerflint/pantsport`
Can I download that model somewhere, or could you send it to me for testing please?

**Comment by JohnnyG4** [comment]
https://drive.google.com/file/d/1ZxNp5VyVFklFOO8EzPxZG8qQdHIKKy-6/view?usp=sharing

**Comment by Silverlan** [comment]
> https://drive.google.com/file/d/1ZxNp5VyVFklFOO8EzPxZG8qQdHIKKy-6/view?usp=sharing

Thanks! I was able to replicate the crash in the latest stable release, but not in the nightly version, so whatever the issue was is already fixed and should work with the next stable release:
![pragma_D8JdR6MsjN](https://github.com/user-attachments/assets/cbf1c290-303d-4e50-abe3-5ef2e1f9707c)

**Comment by JohnnyG4** [comment]
My problem was on the stable release...1.3.0 to be exactly...i'll see what i can do. Thanks.
