### ISSUE TITLE
[BUG] FOV slider on camera from imported SFM sessions isn't working properly

### ISSUE THREAD

**Issue by NeoLin7812** [Silverlan/pfm#4]
**General**
 - Pragma / PFM Version: "v0.4.2, 246757e [P v1.0.5 Win64, 8740fab]"

**Describe the bug**
The FOV slider on camera from imported SFM sessions isn't working properly.

**To Reproduce**
1. Import a SFM session with a camera
2. Select the camera's FOV slider
3. Drag the FOV slider

**Expected behavior**
When sliding the FOV slider, the camera view flickers and won't show the proper view of the camera.

**Screenshots**
https://github.com/Silverlan/pfm/assets/93471777/e14a876f-6ebe-486e-a62d-b2b9f4c67ee6

**Hardware (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA RTX 2070
 - GPU Driver version:  31.0.15.3118

**Log**
[log.txt](https://github.com/Silverlan/pfm/files/11949662/log.txt)

**Additional context**
Also for some reason my character model isn't imported properly, despite everything else is imported correctly.

**Comment by Silverlan** [comment]
I'm closing this, since it should be fixed now.
