### ISSUE TITLE
Asset browser and Bone Merger

### ISSUE THREAD

**Issue by reinboa** [Silverlan/pfm#7]
- Asset Browser akin to s2fm: Not sure how long it would take but it would be beneficial to have for those who have a ton of assets to go through

- A bone merging system like in SFM or tool like in gmod

**Comment by Silverlan** [comment]
I've never used s2fm, what features does the asset browser have that are missing in PFM?

**Comment by reinboa** [comment]
Below is the asset browser in HLA

<img width="1018" alt="Screenshot 2023-11-19 113753" src="https://github.com/Silverlan/pfm/assets/151443849/3e622249-b757-41e6-ab3a-93cb69bc2272">

Just like for sfm you can search for whatever model that you have and it will appear. And like PFM it also has thumbnails. You can have them listed as a list or grid format. You can check out S2FM with CS2 if you want. You just need to download the workshop tools.

**Comment by Silverlan** [comment]
So, are you just looking for a list view and the sort options, or something else as well?

**Comment by Silverlan** [comment]
I'm closing this issue as both features are implemented.

To use the bone-merging system, you can simply drag-and-drop the object you want to bone-merge from the model explorer onto the actor you want to merge it with.
